page:
  size: 8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sw_copy_from_aliyun?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB